### ISSUE TITLE
Plugin Menu could not be found

### ISSUE THREAD

**Issue by Fuhrmann** [VolantisDev/CakePHP-Menu-Plugin#5]
Strange...when I declare the helper MenuBuilder.MenuRenderer:

<code>public $helpers = array('MenuBuilder.MenuRenderer');</code>

I receive this error:

<b>Plugin Menu could not be found.</b>

Looks like something is trying to call a plugin named "Menu". Just dont know why.

**Comment by ReplicaObscura** [comment]
@Fuhrmann 

This plugin's name actually is 'Menu' and not 'MenuBuilder'.

Your $helpers should be declared like this:

```
public $helpers = array('Menu.MenuRenderer');
```

And you should be sure the plugin's folder is named 'Menu' and not 'MenuBuilder'.

I will be rewriting the documentation for this plugin this week since it just underwent a full rewrite, so I apologize if the docs are in a really bad state at the moment :(

**Comment by ReplicaObscura** [comment]
Just to ensure that you had the other piece in place too, there is also a Component named MenuBuilder which can be loaded such as:

```
public $components = array('Menu.MenuBuilder');
```

That component is where you would set up your menu structure, and then use MenuRenderer to output it in your layout or views.

**Comment by Fuhrmann** [comment]
Thank you bmcclure! I was getting hopeless how to solve this error...

While I'm waiting for the documentation, I'll do some tests! ;) Don't worry. You have done an amazing job with this plugin. I just have to thank you for helping me now and for developed this plugin. 

I'll do the changes now and report back.

**Comment by Fuhrmann** [comment]
I have made the changes but still getting an error, take a look:

<code>Fatal error: Class 'DefaultMenuItemRenderer' not found in \sgc\app\Plugin\Menu\View\Helper\MenuRendererHelper.php on line 96</code>

This is my plugin folder:

http://i49.tinypic.com/2ijg511.png

This is what I have in my AppController:

<code>
/\* Componentes usados no controller */
    public $components = array (
        'Acl',
        'Auth' => array (
            'authorize' => array (
                'Actions' => array('actionPath' => 'controllers', 'userModel' => 'Usuario'),
            )
        ),
        'Session',
        'Menu.MenuBuilder'
    );
</code>

And this too, calling the helper:

<code>public $helpers = array('Menu.MenuRenderer');</code>

And this in my bootstrap file:

<code>CakePlugin::load('Menu');</code>

And this is my error log:
<code>
2012-08-27 22:58:07 Error: Fatal Error (64): Can't inherit abstract function MenuItemRenderer::render() (previously declared abstract in BaseMenuItemRenderer) in [\sgc\app\Plugin\Menu\Lib\MenuLib\MenuItemRenderer\BaseMenuItemRenderer.php, line 7]
2012-08-27 22:58:07 Error: [FatalErrorException] Can't inherit abstract function MenuItemRenderer::render() (previously declared abstract in BaseMenuItemRenderer)
#0 \sgc\lib\Cake\Error\ErrorHandler.php(162): ErrorHandler::handleFatalError(64, 'Can't inherit a...', 'C:\xampp\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(64, 'Can't inherit a...', 'C:\xampp\htdocs...', 7, Array)
#2 \sgc\lib\Cake\Core\App.php(926): call_user_func('ErrorHandler::h...', 64, 'Can't inherit a...', 'C:\xampp\htdocs...', 7, Array)
#3 \sgc\lib\Cake\Core\App.php(899): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

</code>

Maybe you could give me a tip again?

**Comment by ReplicaObscura** [comment]
Hmm,

It looks like it's most likely a missing App::uses in the Menu plugin. I'll take a look at that today or tomorrow at the latest to see what might be going on.

In the meantime, you should be able to add this to your AppController:

```
App::uses('DefaultMenuItemRenderer', 'Menu.Lib/MenuLib/MenuItemRenderer');
```

If there are any other similar issues, the same style of App::uses call should work. For instance, if you get an error about DefaultMenuRenderer you could use:

```
App::uses('DefaultMenuRenderer', 'Menu.Lib/MenuLib/MenuRenderer');
```

I'll get these fixed ASAP so that you don't need to add these extra lines to your app in the future.

Thanks for reporting!

**Comment by ReplicaObscura** [comment]
I'm having trouble reproducing your error, so let me know if the above App::uses() lines fix it for you or not.

Those lines already exist in MenuRendererHelper, which seems to be where the error is coming from, so I'm not sure why it's unable to find the class. Just to verify, does the following file exist in your plugin path?

Menu/Lib/MenuLib/MenuItemRenderer/DefaultMenuItemRenderer.php

**Comment by Fuhrmann** [comment]
That's very strange. I may be doing something wrong or it is some configuration problem...

My Plugin Folder:
http://i48.tinypic.com/34yu0so.png

My App Controller:
http://i48.tinypic.com/15btjb.png

The file DefaultMenuItemRenderer.php:
http://i46.tinypic.com/mlo40n.png

My bootstrap file:
http://i47.tinypic.com/9uos2d.png

But for some reason, I'am still receiving the error, take a look:
http://i50.tinypic.com/2epmya0.png

Thank you for your patience!

**Comment by ReplicaObscura** [comment]
Sorry for the delay. I am still trying to figure out how to reproduce this error, or what the difference might be between your application and the ones I've been testing the plugin with.

It seems as if Cake's autoloader is unable to locate the DefaultMenuItemRenderer class, but the App::uses('DefaultMenuItemRenderer', 'Menu.Lib/MenuLib/MenuItemRenderer') line should be informing the autoloader where to find it.

I will try to do a bit more troubleshooting today to see if I can figure out what's happening. Sorry for the delay, and hopefully we can get this resolved soon!

Ben

**Comment by Fuhrmann** [comment]
Hello Ben. That's ok, there is no hurry.

I'll take a look again at my code, I may have missed something!

Thank you!

**Comment by ReplicaObscura** [comment]
I think I ran into the same issue you had with this plugin with the other plugin I just rewrote, AutoAsset.

I still don't know what's wrong, but it's something to do with the way that my classes are requiring files. It seems to be related to the interfaces that the classes within the library implement (the errors go away if they don't implement an interface, but then functionality is hindered).

The kicker is, this only seems to be an issue on the 5.3.8 version of php that was installed on my Ubuntu web server. When I upgraded to PHP 5.4, the plugin started working immediately.

None of my plugins should actually require 5.4, however--they are only using PHP 5.3 features, so I can not yet explain why it doesn't seem to work on certain versions of PHP 5.3. Is it possible you are also on PHP 5.3, and if so, what specific version?

Thanks!

**Comment by Fuhrmann** [comment]
Hello Ben. Thanks for the info.

I'm running PHP 5.3.8 on localhost (Windows). I also have only two plugins: AclExtras and yours (Menu). 

I just created a new CakePHP project from scratch, with no plugins and no configuration changes, just your Menu plugin. But unfortunally I'm still getting the same error!

I'm still trying  to understand what could be this error. Thanks again!

**Comment by ReplicaObscura** [comment]
From what I've found so far, it seems like it's nothing that you're doing wrong. On either PHP 5.3.8, or perhaps all versions of PHP 5.3.x, both my Menu plugin and AutoAsset plugins are getting Class Not Found errors.

It seems to be related to the way (or order) in which I'm including the class files, and the fact that the classes are implementing an interface that's also being included seems to have something to do with it. I'll be working on solving this issue today if possible.

So far I don't know what the issue even is--I am including the interfaces first, followed by the abstract and base classes, followed by the concrete classes, and as far as I know that's the correct order to include everything. I've found a few bug reports of other similar issues with certain versions of PHP 5.3, however, so I'm going to see if any of those solutions work for this case.

Thanks very much for your patience, and your interest in using this plugin--it'll be great when it's fully working to get your feedback on how you're using it!

Ben

**Comment by Fuhrmann** [comment]
Ok Ben! I'll be waiting here.

No problem, take your time. And yes, when we got this working on my system, I'll give you a feedback!

Thanks, Ben!

**Comment by ReplicaObscura** [comment]
When you have a moment, can you check if the latest release resolves the errors you're getting? It's working now on my test machine, but since it's a different test machine than the one that was failing before, I'd appreciate a confirmation either way.

All I ended up doing, and I hope it really is as simple as this, is adding App::uses lines within the Component and Helper for every class that is used directly or indirectly (meaning interfaces and base classes are declared there as well now).

Thanks!

-Ben

**Comment by Fuhrmann** [comment]
Hello Ben! I just tested the new release and still getting the error on my system.

<code>Fatal error: Class 'DefaultMenuItemRenderer' not found in \fuhrmann\sgc\app\Plugin\Menu\View\Helper\MenuRendererHelper.php on line 98</code>

I have created a new cakephp project again from scracth and just received the same error. I'm sure I did copy and paste all the files from the new release...

This could be something related with my Apache configuration? Or even with PHP? 

When I delete this line of my project:

<code>public $helpers = array('Menu.MenuRenderer');</code>

The error no longer appears.

Oh, I'm using CakePHP 2.2.1.

---- Update ----

Just for testing I've added this line, just before create a new instance of DefaultMenuItemRenderer:

<code>include(APP . 'Plugin\Menu\Lib\MenuLib\MenuItemRenderer\DefaultMenuItemRenderer.php');</code>

Now, the error I get is this:

<code>Fatal error: Can't inherit abstract function MenuRenderer::render() (previously declared abstract in BaseMenuRenderer) in fuhrmann\sgc\app\Plugin\Menu\Lib\MenuLib\MenuRenderer\BaseMenuRenderer.php on line 8</code>

**Comment by Fuhrmann** [comment]
Update 2:

Okay, so I have created a new project from scratch using CakePHP. I uploaded your plugin into this new project and got the same two errors: "'DefaultMenuItemRenderer' not found" and "Fatal error: Can't inherit abstract function MenuRenderer::render()".

So, I edited the files BaseMenuRenderer and BaseMenuItemRenderer and just commented this piece of code:

<code>abstract function render(MenuItem $item, MenuRenderer $childRenderer = NULL);</code>

After this change, I dont have errors anymore. Even that  error saying that the "DefaultMenuItemRenderer" was not found.

But, I can not test if the menu is rendering, because I really dont know how to do this.

Thanks again Ben!

**Comment by ReplicaObscura** [comment]
Thanks very much for your work troubleshooting this. My time's been very limited lately and this one has me pretty stumped.

Your solution seems to be the right one, however. I found confirmation in a PHP documentation comment here: http://www.php.net/manual/en/language.oop5.abstract.php#78388

I'm going to not redeclare my interface's methods as abstract methods within the base class.

To give you the ultra-quick rundown of a simple way to use the plugin so you can test it out:
1. In your AppController's beforeFilter, try something like this:
   
   <code>
   $this->MenuBuilder->menu('main', array(
       array(
           'title' => 'Home',
           'url' => array('controller' => 'pages', 'action' => 'display', 'home'),
       ),
       array(
           'title' => 'Test Item',
           'url' => '/',
       ),
   ));
   </code>
2. In your layout, try something like this:
   
   <code>
   $this->MenuRenderer->render('main');
   </code>

If all goes well (and i haven't made any mistakes above, heh), you should render a single menu as an unordered list within a 'nav' element containing two items both pointing to the homepage.

There are a lot more things that you can do to change the behavior, and you can add individual menu items to existing menus and other operations besides just creating an entire menu with one command. I will go into more detail about the available operations as soon as I can find time to update the docs.

Thanks very much again for your assistance troubleshooting this, I was starting to get a bit frustrated with not being able to track that down :)

Ben

**Comment by Fuhrmann** [comment]
Hello Ben!

Sorry I can only answer today. I did the tests as you said and everything worked! The plugin is working normally now.

In short, the only change I had to make was in the BaseMenuRenderer and BaseMenuItemRenderer file, commenting out the line:

<code>abstract function render ($ MenuItem item, $ MenuRenderer childRenderer = NULL);</code>

I'll study better your  plugin, which is working now, and try to use all its features! Thank you for your attention and patience too!

**Comment by ReplicaObscura** [comment]
Thanks very much for following up--it's a relief that it's working now for you. I believe the change you made should be made by default in the latest release of the plugin, so hopefully it is able to work for everyone now.

I plan to make one breaking change soon, which will be to change MenuRendererHelper->render() to MenuRendererHelper->menu(). When using PHP5's Strict mode, currently you are given a warning because render() overrides the base Helper class's render method. Since my render method does not serve the same purpose and does not have the same parameters, I figure I should change this.

Other than that, I plan to take some time by this weekend to rewrite the documentation for the Menu plugin, so if you're still figuring things out by then it should hopefully give you a better idea how to use the more advanced functionality.

Thanks again for sticking with it through these issues, and feel free to post any other questions or requests you might have. I'm always interested in making the plugin better :)

Ben

**Comment by Fuhrmann** [comment]
Hello Ben!

Thank you for the feedback. And yes, I'm trying figuring out how to use some features from this plugin, like the permission system. I am not able to get the checking permissions working. But I can wait until the documentation is ready, so I can learn how to use it.

Another problem I had was with a conflict of class names. In your plugin there is a class called Menu. In the system I'm doing, also exists, which is a model.

Then, within a controller when I'm going to call my model:

<code>$this->Menu</code>

I get an error, because CakePHP looks for the Menu class inside your plugin, and not my Menu Model class.
I wonder if there may be some other solution to this little problem, besides rename my model class.

Thanks!

**Comment by ReplicaObscura** [comment]
Hmm, good question! I never considered that, but it is something I think I should address on the plugin side, as you shouldn't have to change the names of your app classes to be compatible with a plugin.

I definitely don't need to make my class library available to the rest of Cake, since it's self-contained within the plugin. Avoiding the App::uses() lines within the MenuBuilderComponent and MenuRendererHelper should fix the issue as long as I start using namespaces for the MenuLib class library (which I probably should have done from the start).

Cake core seems to use namespaces a lot to allow short class names, so I'll experiment with doing the same thing for MenuLib. If I get some time tomorrow I'll get a new version posted and will update this issue when it's up.

Thanks again!

**Comment by Fuhrmann** [comment]
Ben, do you think there is a quick solution to the conflicted class names problem?

**Comment by ReplicaObscura** [comment]
Sorry for the delay. There may be an easy solution--I'm going to try to implement namespacing to the MenuLib library and always reference the classes by a namespace path. I am hoping that will make Cake's autoloader load the proper model class when requested since MenuLib's class will only be known by full namespace outside of the library.

I'm fairly new to using namespaces in PHP (though I'm very familiar with them in several other languages) so it may take a little while, but I will try to have a solution in place for this today.

**Comment by ReplicaObscura** [comment]
I've opened a new issue for this in #11 since this ticket was originally for a different problem.

I'll update the other ticket as soon as I've got the namespace solution implemented so that you can try it out.

Thanks.

**Comment by ReplicaObscura** [comment]
FYI, I have updated #11 but wanted to make sure you were aware in case you aren't getting notifications on that ticket.

I've implemented namespaces for MenuLib. Whenever you've got a chance, let me know if it's working for you now without name conflicts.

Note the new bootstrap.php file within the Menu plugin... make sure you tell CakePlugin::load (or loadAll) to load the bootstrap file for the Menu plugin so that there are no issues finding MenuLib's classes.

**Comment by SchizoDuckie** [comment]
Pardon my french, but this project is in a messy state.

The docs are not up to date, i have to read from this ticket that the whole shebang has changed, and with the namespaces introduced i cannot seem to solve the 'class DefaultMenuItemRenderer' bug with the app:uses suggestions.

My Patch, I hope this helps others: 

include(APP . 'Plugin/Menu/Lib/MenuLib/MenuRenderer/MenuRendererInterface.php');
include(APP . 'Plugin/Menu/Lib/MenuLib/MenuRenderer/BaseMenuRenderer.php');
include(APP . 'Plugin/Menu/Lib/MenuLib/MenuRenderer/DefaultMenuRenderer.php');
include(APP . 'Plugin/Menu/Lib/MenuLib/MenuItemRenderer/MenuItemRendererInterface.php');
include(APP . 'Plugin/Menu/Lib/MenuLib/MenuItemRenderer/BaseMenuItemRenderer.php');
include(APP . 'Plugin/Menu/Lib/MenuLib/MenuItemRenderer/DefaultMenuItemRenderer.php');

Please fix!

(Besides that: Awesome work!)

Update: Fixed the autoloader not working.

In your bootstrap.php , add 

CakePlugin::load('Menu', array('bootstrap'=> true));

**Comment by ReplicaObscura** [comment]
I know, sorry about that!

I made many changes to the project during my work on a recent Cake project for the company I work for, but didn't have a chance to rewrite the documentation at that time and have neglected it since then.

The autoloader was one of those changes, and I feel bad for not mentioning that the bootstrap file is required for it to work.

I'll see about getting the documentation updated today, or at least over the weekend, to try and make it easier for people who didn't develop it to use it.

Thanks very much for sticking with the project and working to figure out how to use it on your own. Once I rewrite the docs I'll try to make a point to update them as things change with the project to avoid having to have everyone poke around the code to figure it out.

**Comment by th-gauweiler** [comment]
If somone else getting here via searching why an import does not work, then visit the new tutorial:

https://github.com/bmcclure/CakePHP-Menu-Plugin/issues/16
